"""
Structured output model for design guidelines generated by the design_planner node.
"""

from typing import List
from pydantic import BaseModel, Field


class SectionBlueprint(BaseModel):
    """Blueprint for a single section of the landing page."""

    section_id: str = Field(
        default="section",
        description="Section identifier (e.g., 'hero', 'features', 'custom-partners-strip')",
    )
    section_name: str = Field(
        default="Section",
        description="Human-readable section name",
    )
    goal: str = Field(
        default="Clarify the objective of this section.",
        description="Business or storytelling goal this section must accomplish.",
    )
    layout: str = Field(
        default="Define composition for this section including layout, grid, and hierarchy.",
        description="Detailed layout and composition description (structure, grid, spacing, hierarchy)",
    )
    styling: str = Field(
        default="Describe the colors, textures, lighting, and layering unique to this section.",
        description="Local styling guidance: palette accents, gradients, textures, lighting, shadows, decorative elements.",
    )
    content: str = Field(
        default="Outline content structure, messaging tone, CTAs, and data references.",
        description="Content structure and copywriting guidance (what elements, tone, CTAs, data sources)",
    )
    interactions: str = Field(
        default="Specify entrance animations, scroll effects, and hover interactions.",
        description="Motion and interaction design (entrance animations, scroll effects, hover states, transitions)",
    )
    assets: str = Field(
        default="No images provided",
        description="Which assets from sectionAssets are used (e.g., 'hero:main images', 'No images provided')",
    )
    responsive: str = Field(
        default="Mobile-first responsive design with appropriate breakpoints",
        description="Mobile and responsive behavior (breakpoint adjustments, stacking, reordering)",
    )
    developer_notes: str = Field(
        default="Implementation notes for the coder building this section as a single component.",
        description="Explicit developer-focused instructions (component structure, Tailwind strategies, data handling).",
    )


class DesignGuidelines(BaseModel):
    """
    Comprehensive design guidelines generated by the design_planner node.
    This structured output is consumed directly by the coder to implement
    fully self-contained section components (no global design system layer).
    """

    # Brand & Theme
    theme: str = Field(default="dark", description="Theme mode: 'light' or 'dark'")
    brand_tone: str = Field(
        default="Unspecified brand tone",
        description="Brand tone and personality (e.g., 'Confident, product-savvy, slightly playful but enterprise-ready')",
    )
    design_pillars: str = Field(
        default="Unspecified design philosophy",
        description="High-level creative pillars and narrative (e.g., 'Studio-grade aura with cinematic lighting and confident copy')",
    )

    visual_language: str = Field(
        default="Describe palette anchors, contrast strategy, and how colors shift across the page.",
        description="Narrative description of the color story and mood (used per section, not as global tokens).",
    )
    typography_notes: str = Field(
        default="Describe font pairings and usage per section.",
        description="Typography guidance (type pairing, casing, tone) without referencing CSS variables.",
    )
    background_strategy: str = Field(
        default="Explain background layering strategy for hero vs supporting sections.",
        description="How backgrounds evolve across the page (animated hero vs static follow-up bands, layering rules).",
    )
    layout_strategy: str = Field(
        default="Summarize pacing, vertical rhythm, and container rules.",
        description="Global layout and spacing notes that every section component must follow.",
    )
    motion_strategy: str = Field(
        default="Subtle, purposeful, respects prefers-reduced-motion",
        description="Overall motion design approach (e.g., scroll choreography, hover vocabulary).",
    )
    cta_strategy: str = Field(
        default="Clarify CTA tone, hierarchy, and placement throughout the page.",
        description="Guidance on CTA styling, frequency, and pairing (primary vs secondary).",
    )
    component_principles: str = Field(
        default="Explain how each section component must remain self-contained with zero shared tokens.",
        description="Rules for implementing components (local styling, no shared utilities, handling of globals.css).",
    )

    # Section Blueprints
    sections: List[SectionBlueprint] = Field(
        default_factory=list,
        description="Detailed blueprints for each section (Nav, landing page sections, Footer) in order",
    )

    page_title: str = Field(
        default="Landing Page", description="Page title for metadata"
    )
    page_description: str = Field(
        default="Generated landing page description",
        description="Page description for metadata",
    )
    accessibility_notes: str = Field(
        default="Ensure WCAG-compliant contrast, focus states, keyboard navigation, and respect prefers-reduced-motion.",
        description="Accessibility considerations (contrast ratios, keyboard nav, ARIA, reduced motion)",
    )

    # Coder Handoff
    coder_instructions: str = Field(
        default="Implement every section as a single, self-contained component using only local styling techniques.",
        description="Explicit marching orders for the coder (component sequencing, architectural warnings).",
    )
