"""
Structured output model for design guidelines generated by the design_planner node.
"""

from pydantic import BaseModel, Field
from typing import List, Optional


class ColorToken(BaseModel):
    """A single color token in the design system."""

    name: str = Field(
        default="color-unnamed",
        description="Token name (e.g., 'brand', 'accent', 'neutral-100')",
    )
    value: str = Field(
        default="#000000",
        description="Color value (hex, rgb, hsl, or CSS variable reference)",
    )
    usage: str = Field(
        default="General use",
        description="When/where to use this color (e.g., 'Primary CTA buttons', 'Body text')",
    )


class TypographySpec(BaseModel):
    """Typography specification for a font family."""

    family: str = Field(
        default="Inter",
        description="Font family name (e.g., 'Inter', 'Playfair Display')",
    )
    weights: List[str] = Field(
        default_factory=lambda: ["400", "600"],
        description="Font weights to load (e.g., ['400', '600', '700'])",
    )
    variable_name: str = Field(
        default="--font-sans",
        description="CSS variable name (e.g., '--font-sans', '--font-heading')",
    )
    usage: str = Field(
        default="General text",
        description="Where to use this font (e.g., 'Body text and UI', 'Headlines and hero text')",
    )


class AnimationSpec(BaseModel):
    """Animation specification for a section or element."""

    type: str = Field(
        ...,
        description="Animation type (e.g., 'fade-in', 'slide-up', 'parallax', 'gradient-shift')",
    )
    target: str = Field(
        ...,
        description="What gets animated (e.g., 'hero background', 'section entrance', 'scroll-triggered cards')",
    )
    duration: Optional[str] = Field(
        default="0.6s", description="Animation duration (e.g., '0.6s', '20s')"
    )
    easing: Optional[str] = Field(
        default="ease-out",
        description="Easing function (e.g., 'ease-out', 'cubic-bezier(0.4, 0, 0.2, 1)')",
    )
    notes: Optional[str] = Field(
        default=None, description="Additional implementation notes"
    )


class SectionBlueprint(BaseModel):
    """Blueprint for a single section of the landing page."""

    section_id: str = Field(
        default="section",
        description="Section identifier (e.g., 'hero', 'features', 'custom-partners-strip')",
    )
    section_name: str = Field(
        default="Section",
        description="Human-readable section name",
    )
    composition: str = Field(
        default="Define composition for this section including layout, grid, and hierarchy.",
        description="Detailed layout and composition description (structure, grid, spacing, hierarchy)",
    )
    background: str = Field(
        default="Describe static background treatment, gradients, and layering.",
        description="Background treatment description (gradients, layers, colors, textures, static/animated)",
    )
    content_guidance: str = Field(
        default="Outline content structure, messaging tone, CTAs, and data references.",
        description="Content structure and copywriting guidance (what elements, tone, CTAs, data sources)",
    )
    motion: str = Field(
        default="Specify entrance animations, scroll effects, and hover interactions.",
        description="Motion and interaction design (entrance animations, scroll effects, hover states, transitions)",
    )
    assets_usage: str = Field(
        default="No images provided",
        description="Which assets from sectionAssets are used (e.g., 'hero:main images', 'No images provided')",
    )
    responsive_notes: str = Field(
        default="Mobile-first responsive design with appropriate breakpoints",
        description="Mobile and responsive behavior (breakpoint adjustments, stacking, reordering)",
    )
    custom_section_notes: Optional[str] = Field(
        default=None,
        description="For custom sections: additional notes from the custom section definition",
    )


class DesignGuidelines(BaseModel):
    """
    Comprehensive design guidelines generated by the design_planner node.
    This structured output will be used by the designer node to implement
    globals.css, tailwind.config.ts, and layout.tsx.
    """

    # Brand & Theme
    theme: str = Field(default="dark", description="Theme mode: 'light' or 'dark'")
    brand_tone: str = Field(
        default="Unspecified brand tone",
        description="Brand tone and personality (e.g., 'Confident, product-savvy, slightly playful but enterprise-ready')",
    )
    design_philosophy: str = Field(
        default="Unspecified design philosophy",
        description="Overall design philosophy and visual direction (e.g., 'Premium, minimal, Apple-inspired with bold typography')",
    )

    # Color System
    colors: List[ColorToken] = Field(
        default_factory=list, description="Complete color token system for the design"
    )

    # Typography
    typography: List[TypographySpec] = Field(
        default_factory=list,
        description="Font families, weights, and usage specifications",
    )

    # Spacing & Layout
    container_max_width: str = Field(
        default="1280px", description="Max container width (e.g., '1280px', '7xl')"
    )
    section_spacing: str = Field(
        default="py-16 md:py-24",
        description="Vertical spacing between sections (e.g., 'py-16 md:py-24', 'Large: 120px, Medium: 80px')",
    )
    grid_system: str = Field(
        default="12-column grid with gap-6 and responsive breakpoints at sm/md/lg/xl",
        description="Grid system approach (e.g., '12-column, gap-6, responsive breakpoints at sm/md/lg/xl')",
    )

    # Components & UI Elements
    button_styles: str = Field(
        default="Refer to design planner instructions for button styles",
        description="Button styling specifications (primary, secondary, sizes, states, padding, rounding)",
    )
    input_styles: str = Field(
        default="Refer to design planner instructions for input styles",
        description="Input/form field styling specifications (borders, focus states, padding, validation)",
    )
    card_styles: str = Field(
        default="Refer to design planner instructions for card styles",
        description="Card component styling (background, borders, shadows, padding, hover states)",
    )

    # Motion & Animation
    animations: List[AnimationSpec] = Field(
        default_factory=list,
        description="Animation specifications for sections and interactions",
    )
    motion_philosophy: str = Field(
        default="Subtle, purposeful, respects prefers-reduced-motion",
        description="Overall motion design approach (e.g., 'Subtle, purposeful, respects prefers-reduced-motion')",
    )

    # Section Blueprints
    sections: List[SectionBlueprint] = Field(
        default_factory=list,
        description="Detailed blueprints for each section (Nav, landing page sections, Footer) in order",
    )

    # Metadata & SEO
    page_title: str = Field(
        default="Landing Page", description="Page title for metadata"
    )
    page_description: str = Field(
        default="Generated landing page description",
        description="Page description for metadata",
    )
    og_tags: Optional[str] = Field(default=None, description="Open Graph tags guidance")

    # Implementation Notes
    tailwind_plugins: List[str] = Field(
        default_factory=list,
        description="Required Tailwind plugins (e.g., '@tailwindcss/forms', 'tailwindcss-animate')",
    )
    css_custom_properties: str = Field(
        default="Define CSS variables for colors, spacing, and typography as specified.",
        description="Custom CSS properties/variables to define in globals.css",
    )
    layout_structure: str = Field(
        default="Use layout.tsx to load fonts, apply body classes, and include metadata per guidelines.",
        description="Layout.tsx structure guidance (fonts, metadata, body classes, global wrappers)",
    )
    accessibility_notes: str = Field(
        default="Ensure WCAG-compliant contrast, focus states, keyboard navigation, and respect prefers-reduced-motion.",
        description="Accessibility considerations (contrast ratios, keyboard nav, ARIA, reduced motion)",
    )

    # Coder Handoff
    coder_instructions: str = Field(
        default="Implement all sections as described in the blueprints using the provided design system.",
        description="Specific instructions for the coder agent on what to implement next",
    )
