from dotenv import load_dotenv
from pydantic import BaseModel, Field
from typing import Annotated, Dict, Any
from langgraph.graph.message import add_messages

load_dotenv()


def replace(a, b):
    return b


class BuilderState(BaseModel):
    """Shared state between Designer, Coder, Clarifier, and other agents in the landing page builder graph."""

    # 🗣️ Core conversational stream
    messages: Annotated[list, add_messages]

    # 🧭 Intent management
    user_intent: Annotated[str, replace]
    found_error: Annotated[bool, replace]

    # 🧰 Diff / change tracking (used by Coder Agent)
    lines_added: Annotated[int, replace]
    lines_removed: Annotated[int, replace]

    # 🎨 Design System (Designer Agent)
    raw_designer_output: Annotated[str, replace] = Field(
        default="",
        description="Raw unstructured output from Designer Agent.",
    )
    design_system_run: Annotated[bool, replace] = Field(
        default=False,
        description="Indicates whether the design system pass has completed for the session.",
    )

    # 💻 Coder Agent
    coder_output: Annotated[str, replace] = Field(
        default="", description="Summary or code changes generated by the Coder Agent."
    )
    coder_run: Annotated[bool, replace] = Field(
        default=False,
        description="Indicates whether the coder pass has completed for the session.",
    )

    # 💬 Clarifier Agent
    clarify_response: Annotated[str, replace] = Field(
        default="",
        description="Response from Clarifier Agent when no code/design action is needed.",
    )

    # 🚀 Initialization Payload
    init_payload: Annotated[Dict[str, Any], replace] = Field(
        default_factory=dict,
        description="Raw structured initialization payload captured from /init endpoint.",
    )
    init_payload_text: Annotated[str, replace] = Field(
        default="",
        description="Flattened textual summary of the initialization payload injected as the first human message.",
    )
