from dotenv import load_dotenv
from pydantic import BaseModel, Field
from typing import Annotated, Dict, Any
from langgraph.graph.message import add_messages

load_dotenv()


def replace(a, b):
    return b


class BuilderState(BaseModel):
    """Shared state between Designer, Coder, Clarifier, and other agents in the landing page builder graph."""

    # 📂 Session management
    session_id: Annotated[str, replace] = Field(
        default="default",
        description="The ID of the session.",
    )
    job_id: Annotated[str | None, replace] = Field(
        default=None,
        description="Optional job id for this graph execution (used for async logging).",
    )

    # 🗣️ Core conversational stream
    messages: Annotated[list, add_messages]

    # 🧭 Intent management
    user_intent: Annotated[str, replace]
    found_error: Annotated[bool, replace]
    is_followup: Annotated[bool, replace] = Field(
        default=False,
        description="Indicates whether the latest user message is a follow-up request.",
    )

    # 🧰 Diff / change tracking (used by Coder Agent)
    lines_added: Annotated[int, replace]
    lines_removed: Annotated[int, replace]

    # 🎨 Design System (Design Planner + Designer Agent)
    design_guidelines: Annotated[Dict[str, Any], replace] = Field(
        default_factory=dict,
        description="Structured design guidelines generated by the design_planner node.",
    )
    design_planner_run: Annotated[bool, replace] = Field(
        default=False,
        description="Indicates whether the design planner has generated guidelines for the session.",
    )
    design_blueprint_markdown: Annotated[str, replace] = Field(
        default="",
        description="Markdown file contents summarizing the design blueprint decisions.",
    )
    design_blueprint_pdf_url: Annotated[str, replace] = Field(
        default="",
        description="Public URL to the uploaded design blueprint PDF in cloud storage.",
    )
    design_blueprint_pdf_run: Annotated[bool, replace] = Field(
        default=False,
        description="Indicates whether the design blueprint PDF generator has completed for the session.",
    )

    # 📈 Data-driven insights
    data_insights: Annotated[Dict[str, Any], replace] = Field(
        default_factory=dict,
        description="Structured campaign/experiment analytics extracted from uploaded datasets.",
    )
    campaign_data_digest: Annotated[str, replace] = Field(
        default="",
        description="Narrative summary of campaign performance data used to inform design decisions.",
    )
    experiment_data_digest: Annotated[str, replace] = Field(
        default="",
        description="Narrative summary of experiment outcomes that should shape page design.",
    )
    data_warnings: Annotated[list[str], replace] = Field(
        default_factory=list,
        description="Warnings or errors encountered while processing uploaded datasets.",
    )

    # 🧱 Section generation
    generated_sections: Annotated[list[dict[str, Any]], replace] = Field(
        default_factory=list,
        description="Structured outputs from the generate_section node for each section.",
    )
    sections_generated: Annotated[bool, replace] = Field(
        default=False,
        description="Indicates whether section generation has completed.",
    )
    codegen_summary: Annotated[str, replace] = Field(
        default="",
        description="Summary message from the codegen node after writing core files.",
    )
    lint_output: Annotated[str, replace] = Field(
        default="",
        description="Raw linting output captured by the linting node.",
    )
    lint_failed: Annotated[bool, replace] = Field(
        default=False,
        description="Indicates whether linting reported errors.",
    )
    fix_errors_run: Annotated[bool, replace] = Field(
        default=False,
        description="Indicates whether the fix_errors node has attempted repairs.",
    )
    fix_errors_read_only_attempts: Annotated[int, replace] = Field(
        default=0,
        description="Counts consecutive read-only fix_errors passes to prevent infinite loops.",
    )

    # 💬 Clarifier Agent
    clarify_response: Annotated[str, replace] = Field(
        default="",
        description="Response from Clarifier Agent when no code/design action is needed.",
    )

    # 🚢 Deployment tracking
    deployment_failed: Annotated[bool, replace] = Field(
        default=False,
        description="Indicates whether the deployment failed and needs fixing.",
    )
    deployment_error: Annotated[str, replace] = Field(
        default="",
        description="Error message from failed deployment attempt.",
    )
    deployment_fixer_run: Annotated[bool, replace] = Field(
        default=False,
        description="Indicates whether the deployment fixer has made changes.",
    )
    deployment_fixer_read_only_attempts: Annotated[int, replace] = Field(
        default=0,
        description="Counts consecutive read-only deployment_fixer passes to prevent infinite loops.",
    )
    deployment_fixer_pass: Annotated[int, replace] = Field(
        default=0,
        description="Tracks the deployment fixer workflow phase: 0=read, 1=write, 2+=auto.",
    )

    # 🚀 Initialization Payload
    init_payload: Annotated[Dict[str, Any], replace] = Field(
        default_factory=dict,
        description="Raw structured initialization payload captured from /init endpoint.",
    )
    init_payload_text: Annotated[str, replace] = Field(
        default="",
        description="Flattened textual summary of the initialization payload injected as the first human message.",
    )
